sudo: required

language: generic

dist:
  xenial

cache:
  directories:
    - $HOME/.m2

services:
  - docker

script:
  - pip install gitchangelog --user -U pip
  - echo 'Running changelog generator test'
