sudo: required

language: generic

git:
  depth: 10

dist:
  xenial

script:
  - gem install github_changelog_generator
  - github_changelog_generator -u yildiz-online -p test-changelog
  - cat /home/travis/build/yildiz-online/test-changelog/CHANGELOG.md
