sudo: required

language: generic

dist:
  xenial

cache:
  directories:
    - $HOME/.m2

services:
  - docker

script:
  - gem install github_changelog_generator
  - echo 'Running changelog generator test'
